baseURL = 'https://mambusskruj.github.io/'
languageCode = 'en-us'
title = 'Home'
languagecode = "en"

pygmentsstyle = "tango"
pygmentscodefences = true

[params]
  sitename = "Home"
  disableWebFonts = true
  dateFormat = "Jan 2006"


[[menu.main]]
  name = "HOME"
  url  = "/"

# [[menu.main]]
#     name = "INFO"
#     url  = "/about/"
